#
# Liebe Studierende,
#
# bitte modifizieren Sie diese Datei NICHT.
#
image: registry.it.hs-heilbronn.de/it/development/git-runners/itadmin-openjdk17_repo-hhnit:latest
stages:
  - a1-checks
  - a2-checks
  - a2-tests
  - a3a-checks
  - a3a-tests
  - a3b-checks
  - a3b-tests
  - a4-checks
  - a4-tests

variables:
  SIMPLE_LOG_PROPERTY: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"

#
# EXERCISE A1
#
script-check-a1:
  image: registry.it.hs-heilbronn.de/it/development/git-runners/itadmin-alpine-psql
  stage: a1-checks
  services:
    - postgres:latest
  variables:
    POSTGRES_DB: pdbg
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: "postgres"
  script:
    - /bin/sh -c "[ -f "A1/ddl/schema.sql" ] || ( echo Datei schema.sql im Ordner A1/ddl existiert nicht. Bitte legen Sie Ihr DDL in dieser Datei ab! && exit 1 )";
    # psql returns 0 to the shell if it finished normally,
    # 1 if a fatal error of its own occurs (e.g., out of memory, file not found),
    # 2 if the connection to the server went bad and the session was not interactive, and
    # 3 if an error occurred in a script and the variable ON_ERROR_STOP was set.
    # https://www.postgresql.org/docs/12/app-psql.html#id-1.9.4.18.7
    - export PGPASSWORD=postgres; psql --single-transaction -h postgres -d pdbg -U postgres -f A1/ddl/schema.sql -v "ON_ERROR_STOP=1"

#
# EXERCISE A2
#
test-jdk17-a2:
  stage: a2-tests
  services:
    - postgres:latest
  variables:
    POSTGRES_DB: pdbg-a2
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: "postgres"
  script:
    - cd A2;
    - mvn initialize -B $SIMPLE_LOG_PROPERTY
    - mvn clean test -Ptests-junit -B $SIMPLE_LOG_PROPERTY
  needs: ["checkstyle-a2"]

checkstyle-a2:
  stage: a2-checks
  script:
    - cd A2;
    - mvn checkstyle:check -Ptool-checkstyle -B $SIMPLE_LOG_PROPERTY
  needs: ["checkstyle-report-a2"]

checkstyle-report-a2:
  stage: a2-checks
  script:
    - cd A2;
    - mvn initialize -B $SIMPLE_LOG_PROPERTY
    - mvn checkstyle:checkstyle -Ptool-checkstyle-reporting -B $SIMPLE_LOG_PROPERTY
    - mvn site -Ptool-checkstyle-reporting -B $SIMPLE_LOG_PROPERTY
  artifacts:
    paths:
      - A2/target/site
    expire_in: 10 minutes
  needs: ["compile-a2"]

compile-a2:
  stage: a2-checks
  script:
    - cd A2;
    - mvn initialize -B $SIMPLE_LOG_PROPERTY
    - mvn compile -B $SIMPLE_LOG_PROPERTY

#
# EXERCISE A3A
#
checkstyle-a3a:
  stage: a3a-checks
  script:
    - cd A3A;
    - mvn checkstyle:check -Ptool-checkstyle -B $SIMPLE_LOG_PROPERTY
  needs: ["checkstyle-report-a3a"]

checkstyle-report-a3a:
  stage: a3a-checks
  script:
    - cd A3A;
    - mvn initialize -B $SIMPLE_LOG_PROPERTY
    - mvn checkstyle:checkstyle -Ptool-checkstyle-reporting -B $SIMPLE_LOG_PROPERTY
    - mvn site -Ptool-checkstyle-reporting -B $SIMPLE_LOG_PROPERTY
  artifacts:
    paths:
      - A3A/target/site
    expire_in: 10 minutes
  needs: ["compile-a3a"]

compile-a3a:
  stage: a3a-checks
  script:
    - cd A3A;
    - mvn initialize -B $SIMPLE_LOG_PROPERTY
    - mvn compile -B $SIMPLE_LOG_PROPERTY

#
# EXERCISE A4A
#
test-perf-a4a:
  stage: a4-tests
  tags:
    - db2
  services:
    - postgres:latest
  variables:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: "postgres"
  before_script:
    - export PGPASSWORD='postgres'; psql -h postgres -U postgres -c 'CREATE DATABASE "pdbg-baseline"';
    - export PGPASSWORD='postgres'; psql -h postgres -U postgres -c 'CREATE DATABASE "pdbg-a4a"';
  script:
    - cd A4A;
    - mvn initialize -B $SIMPLE_LOG_PROPERTY
    - mvn clean test -Pa4-performance-tests -B $SIMPLE_LOG_PROPERTY
  needs: ["test-jdk17-a4a"]

test-jdk17-a4a:
  stage: a4-tests
  services:
    - postgres:latest
  variables:
    POSTGRES_DB: pdbg-a4a
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: "postgres"
  script:
    - cd A4A;
    - mvn initialize -B $SIMPLE_LOG_PROPERTY
    - mvn clean test -Pa2-unit-tests -B $SIMPLE_LOG_PROPERTY
  needs: ["checkstyle-a4a"]

checkstyle-a4a:
  stage: a4-checks
  script:
    - cd A4A;
    - mvn checkstyle:check -Ptool-checkstyle -B $SIMPLE_LOG_PROPERTY
  needs: ["checkstyle-report-a4a"]

checkstyle-report-a4a:
  stage: a4-checks
  script:
    - cd A4A;
    - mvn initialize -B $SIMPLE_LOG_PROPERTY
    - mvn checkstyle:checkstyle -Ptool-checkstyle-reporting -B $SIMPLE_LOG_PROPERTY
    - mvn site -Ptool-checkstyle-reporting -B $SIMPLE_LOG_PROPERTY
  artifacts:
    paths:
      - A4A/target/site
    expire_in: 10 minutes
  needs: ["compile-a4a"]

compile-a4a:
  stage: a4-checks
  script:
    - cd A4A;
    - mvn initialize -B $SIMPLE_LOG_PROPERTY
    - mvn compile -B $SIMPLE_LOG_PROPERTY
